routes/web.php
<?php

use App\Http\Controllers\Front\ArticleController;
use App\Http\Controllers\Front\AuthController;
use App\Http\Controllers\Front\AuthorController;
use App\Http\Controllers\Front\CartController;
use App\Http\Controllers\Front\CKEditorController;
use App\Http\Controllers\Front\CommentController;
use App\Http\Controllers\Front\HeaderController;
use App\Http\Controllers\Front\HomeController;
use App\Http\Controllers\Front\InvoicesController;
use App\Http\Controllers\Front\PageController;
use App\Http\Controllers\Front\PaymentsController;
use App\Http\Controllers\Front\ProductController;
use App\Http\Controllers\Front\TagController;
use App\Jobs\UploadFile;
use Carbon\Carbon;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/render-header-categories/{category}', [HeaderController::class, 'renderHeaderCategories'])
    ->name('render-header-categories');

/* Authentication */
Route::prefix('ajax')->group(function () {
    Route::get('login-view', [AuthController::class, 'loginView'])->name('ajax.login.view');
    Route::post('login', [AuthController::class, 'doLogin'])->name('ajax.login');
    Route::get('register-view', [AuthController::class, 'registerView'])->name('ajax.register.view');
    Route::post('send-verify-code', [AuthController::class, 'sendVerifyCode'])->name('ajax.send_verify_code');
    Route::post('verify', [AuthController::class, 'doVerify'])->name('ajax.verify');
    Route::post('register', [AuthController::class, 'doRegister'])->name('ajax.register');
    Route::get('change-password.view', [AuthController::class, 'changePasswordView'])->name('ajax.change_password_view');
    Route::post('change-password-step-1', [AuthController::class, 'changePasswordStep1'])->name('ajax.change_password_1');
    Route::post('change-password-step-2', [AuthController::class, 'changePasswordStep2'])->name('ajax.change_password_2');
    Route::post('change-password-step-3', [AuthController::class, 'changePasswordStep3'])->name('ajax.change_password_3');
});
Route::get('email/verify/{token}', [AuthController::class, 'verifyEmail'])->name('email.verify');

/* Blog */
Route::prefix('blog')->group(function () {
    Route::get('/', [ArticleController::class, 'index'])->name('blog.index');
    Route::get('{article}', [ArticleController::class, 'show'])->name('blog.show');
});

/* Products */
Route::get('search', [ProductController::class, 'index'])->name('products.index');
Route::get('category/{category:slug}', [ProductController::class, 'archive'])->name('products.archive');
Route::get('p/{id}/{slug}', [ProductController::class, 'show'])->name('products.show');
Route::get('download/{product}', [ProductController::class, 'download'])->name('products.download');

/* CKEditor Upload Image */
Route::post('ckeditor/upload', [CKEditorController::class, 'upload'])->name('ckeditor.upload');

/* Purchase */
Route::middleware('auth')->group(function () {
    Route::get('cart', [CartController::class, 'index'])->name('cart');
    Route::post('add-to-cart/{product}', [CartController::class, 'addToCart'])->name('addToCart');
    Route::delete('delete-from-cart/{id}', [CartController::class, 'destroy'])->name('deleteFromCart');
    Route::post('invoices', [InvoicesController::class, 'store'])->name('invoice.store');
    Route::get('invoices/{invoice}/pay', [InvoicesController::class, 'pay'])->name('invoice.pay');
    Route::any('payments/{payment}/verify', [PaymentsController::class, 'verify'])->name('payment.verify');
    Route::get('receipt', [CartController::class, 'receipt'])->name('receipt');
});

/* Pages */
Route::get('page/{slug}', [PageController::class, 'show'])->name('page.show');
Route::get('empty-page', [PageController::class, 'emptyPage'])->name('emptyPage');
/* Author */
Route::get('author/{username}', [AuthorController::class, 'show'])->name('author.show');

/* Comments */
Route::post('comment/store', [CommentController::class, 'store'])->name('comment.add');

/* Tags */
Route::get('suggestion-tags', [TagController::class, 'suggestionTags'])->name('suggestionTags');

/* Clear Cache */
Route::get('/cache-clear', function () {
    Artisan::call('cache:clear');
    Artisan::call('route:cache');
    Artisan::call('view:clear');
    Artisan::call('config:cache');

    dd("cache clear All");
});

/* Admin Panel */
include __DIR__ . '/include/admin_routes.php';

/* Dashboard */
include __DIR__ . '/include/dashboard_routes.php';

require __DIR__ . '/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'username', 'email', 'phone', 'avatar', 'IBAN',
        'state', 'city', 'is_admin', 'password', 'total_revenue', 'outstanding',
        'email_verified_at', 'phone_verified_at', 'is_email_verified'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'phone_verified_at' => 'datetime',
        'total_revenue' => 'integer',
        'outstanding' => 'integer',
        'is_admin' => 'boolean'
    ];

    public function tokens(): HasMany
    {
        return $this->hasMany(Token::class);
    }

    public function getFullNameAttribute(): string
    {
        return "{$this->first_name} {$this->last_name}";
    }

    public function articles(): HasMany
    {
        return $this->hasMany(Article::class);
    }

    public function getAdjustedAvatarAttribute(): string
    {
        return isset($this->avatar) ?
            env('STORAGE_ADDRESS') . env('AVATARS') . $this->avatar :
            asset('assets/front/images/no-photo.jpg');
    }

    public function tickets(): HasMany
    {
        return $this->hasMany(Ticket::class);
    }

    /* User's products */
    public function products(): HasMany
    {
        return $this->hasMany(Product::class);
    }

    public function awards(): BelongsToMany
    {
        return $this->belongsToMany(Award::class, 'award_user');
    }

    public function cartProducts(): HasMany
    {
        return $this->hasMany(Cart::class);
    }

    public function invoices(): HasMany
    {
        return $this->hasMany(Invoice::class);
    }

    /* User's purchased products */
    public function purchasedProducts(): BelongsToMany
    {
        return $this->belongsToMany(Product::class, 'product_user')
            ->withPivot(['product_price', 'product_name']);
    }

    public function purchased($id): bool
    {
        return $this->purchasedProducts()->where('id', $id)->count() > 0;
    }

    public function withdraws(): HasMany
    {
        return $this->hasMany(Withdraw::class);
    }
}

app/Http/Controllers/Back/DashboardController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Payment;
use App\Models\Ticket;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Morilog\Jalali\Jalalian;

class DashboardController extends Controller
{
    public function index()
    {
        $payments = Payment::where('status', Payment::STATUS_SUCCEED)->latest()->limit(5)->get();
        $tickets = Ticket::whereNull('parent_id')->latest('updated_at')->limit(5)->get();
        $chartData = $this->chart()->getData();
        $pDates = $chartData->pDates;
        $pCount = json_encode($chartData->pCount);
        $pAmount = json_encode($chartData->pAmount);
        return view('back.index', compact(['payments', 'tickets', 'pDates', 'pCount', 'pAmount']));
    }

    public function chart()
    {
        $md = jdate()->subYears()->format('Y-m-d');
        $payments = Payment::where('status', Payment::STATUS_SUCCEED)->whereDate('jdate', '>=', $md)
            ->latest()->select('id', 'invoice_id', 'jdate');

        $pDates = [];
        $pCount = [];
        $pAmount = [];

        for ($i = 0; $i < 12; $i++) {
            if ($i == 0) {
                $end = jdate()->format('Y-m-d');
                $start = jdate()->subDays(jdate()->getDay() - 1)->format('Y-m-d');
            } else {
                $end = Jalalian::fromFormat('Y-m-d', $start)->subDays()->format('Y-m-d');
                $start = Jalalian::fromFormat('Y-m-d', $start)->subMonths()->format('Y-m-d');
            }

            array_push($pDates, Jalalian::fromFormat('Y-m-d', $start)->format('%B'));
            $pim = $payments->whereBetween('jdate', [$start, $end]);
            $aim = 0; // Amount (price) given in this month.
            $salesNum = 0; // Sales number.
            foreach ($pim->get() as $p) {
                $aim += $p->invoice->amount;
                $salesNum += $p->invoice->products->count();
            }
            array_push($pAmount, $aim);
            array_push($pCount, $salesNum);
        }

        return response()->json([
            'pDates' => array_reverse($pDates),
            'pCount' => array_reverse($pCount),
            'pAmount' => array_reverse($pAmount)
        ]);
    }
}

app/Http/Controllers/Front/ArticleController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\Article;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    public function index(Request $request)
    {
        $page_title = 'لیست مطالب';
        $query = Article::query();
        if ($request->has('s')) {
            $query->where('title', 'LIKE', "%{$request->input('s')}%")
                ->orWhere('name', 'LIKE', "%{$request->input('s')}%")
                ->orWhere('content', 'LIKE', "%{$request->input('s')}%")
                ->orWhere('tags', 'LIKE', "%{$request->input('s')}%");
        }
        $articles = $query->orderByDesc('updated_at')->paginate(11);
        $best_articles = Article::orderBy('views', 'desc')->take(5)->get();
        return view('front.blog.index', compact('page_title', 'articles', 'best_articles'));
    }

    public function show($slug)
    {
        $article = Article::where('slug', $slug)->firstOrFail();
        $page_title = $article->title ?? $article->name;
        $latest_articles = Article::orderByDesc('updated_at')->take(6)->get();
        $comments = $article->comments()->whereNull('parent_id')->where('status', 1)->latest()->paginate(10);
        return view('front.blog.single', compact('page_title', 'article', 'latest_articles', 'comments'));
    }
}

app/Http/Controllers/Front/AuthorController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class AuthorController extends Controller
{
    public function show(Request $request, $username)
    {
        $user = User::where('username', $username)->firstOrFail();
        $page_title = $user->full_name;
        $products = $user->products()->where('status', 2)->filter($request->all())->paginateFilter(30);
        $productsCount = $user->products()->where('status', 2)->count();
        return view('front.author', compact('page_title', 'user', 'products', 'productsCount'));
    }
}

app/Http/Controllers/Front/CKEditorController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\ContentImage;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;

class CKEditorController extends Controller
{
    public function upload(Request $request): JsonResponse
    {
        if ($request->hasFile('upload')) {
            $file = $request->file('upload');
            $img = Image::make($file);
            $img->height() > 1920 ? $img->resize(1920, null, function ($constraint) {
                $constraint->aspectRatio();
            })->encode('jpg', 80) : $img->encode('jpg', 80);
            $uniqueID = uniqid();
            $userID = Auth::id();
            $str = Str::random(4);
            $fileName = "u{$userID}-{$uniqueID}-{$str}.jpg";
            Storage::disk('ftp')->put(env('PRODUCTS_CONTENT') . $fileName, $img);

            $url = env('STORAGE_ADDRESS') . env('PRODUCTS_CONTENT') . $fileName;

            // Add to content_images table for manage unused media
            ContentImage::create([
                "fileName" => $fileName,
                "url" => $url
            ]);
        }

        return response()->json(['url' => $url]);
    }
}

app/Http/Controllers/Front/CartController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\Cart;
use App\Models\Payment;
use App\Models\Product;
use Exception;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CartController extends Controller
{
    public function index()
    {
        $page_title = 'سبد خرید';
        $products = Auth::user()->cartProducts;
        $total_price = 0;
        return view('front.cart', compact('page_title', 'products', 'total_price'));
    }

    public function addToCart(Request $request, Product $product): RedirectResponse
    {
        if (Auth::user()->cartProducts()->where('product_id', $product->id)->count() > 0) {
            return back()->with(['info' => 'این محصول در سبد خرید شما موجود است.']);
        }
        try {
            Cart::create([
                'product_id' => $product->id,
                'user_id' => Auth::id()
            ]);
        } catch (Exception $exception) {
            return back()->with(['error' => 'مشکلی به وجود آمده است! لطفا بعدا دوباره امتحان کنید.']);
        }
        return back()->with(['success' => 'محصول با موفقیت به سبد خرید شما اضافه شد.']);
    }

    public function destroy($id): RedirectResponse
    {
        $cartProduct = Auth::user()->cartProducts()->where('product_id', $id)->firstOrFail();
        try {
            $cartProduct->delete();
        } catch (Exception $exception) {
            return back()->with(['error' => 'مشکلی به وجود آمده است! لطفا بعدا دوباره امتحان کنید.']);
        }
        return back()->with(['success' => 'محصول مورد نظر از سبد خرید شما حذف گردید.']);
    }

    public function receipt(Request $request)
    {
        if (!$request->has('transaction')) {
            return back()->with(['info' => 'شما دسترسی لازم به این صفحه را ندارید!']);
        }
        $payment = Payment::where('transaction', $request->input('transaction'))->firstOrFail();
        if ($payment->invoice->user_id != Auth::id()) {
            return back()->with(['info' => 'شما دسترسی لازم به این صفحه را ندارید!']);
        }
        $page_title = 'رسید تراکنش';
        return view('front.receipt', compact('payment', 'page_title'));
    }
}

app/Http/Controllers/Front/Dashboard/OrderController.php
<?php

namespace App\Http\Controllers\Front\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Payment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OrderController extends Controller
{
    public function index()
    {
        $page_title = 'سفارشات';
        $invoices = Auth::user()->invoices()->latest()->paginate(15);
        return view('front.dashboard.orders.index', compact('page_title', 'invoices'));
    }

    public function show(Payment $payment)
    {
        $page_title = 'مشاهده سفارش';
        return view('front.dashboard.orders.show', compact('page_title', 'payment'));
    }
}

app/Http/Controllers/Front/HeaderController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class HeaderController extends Controller
{
    public function renderHeaderCategories(Request $request, Category $category): JsonResponse
    {
        if ($request->ajax()) {
            $view = view('front.layouts.header-category-items', compact('category'))->render();
            return response()->json(['html' => $view]);
        }
        return response()->json(['error' => 'You have not right access!'], 422);
    }
}

app/Http/Controllers/Front/PageController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\Page;
use Illuminate\Http\Request;

class PageController extends Controller
{
    public function show($slug)
    {
        $page = Page::where('slug', $slug)->firstOrFail();
        $page_title = $page->title ?? $page->name;
        return view('front.page', compact('page_title', 'page'));
    }

    public function emptyPage()
    {
        $page_title = 'برگه';
        return view('front.empty', compact('page_title'));
    }
}

resources/views/front/dashboard/edit-phone.blade.php
@extends('front.layouts.app')
@section('content')
    <section class="single_content">
        <div class="container">
            <div class="fes-vendor-dashboard-wrap row">
                @include('front.layouts.dashboard-sidebar')
                <div class="fes-vendor-dashboard col-md-9">
                    <div class="single_description marg_top_20 rounded shadow">
                        <div class="description_product negarbin_all_vendor_dashboard negarbin_left_dashboard">
                            <form action="{{route('dashboard.profile.updatePhone')}}" method="post">
                                @csrf
                                <div class="my-2">
                                    @include('front.layouts.notification')
                                    @if ($errors->any())
                                        <div class="alert alert-danger">
                                            @foreach ($errors->all() as $error)
                                                <li class="m-0">{{ $error }}</li>
                                            @endforeach
                                        </div>
                                    @endif
                                </div>
                                <label>
                                    <h6>ویرایش شماره موبایل : </h6>
                                    <div class="negarbin_dashboard_field">
                                        <input type="text" name="phone"
                                               value="{{auth()->user()->phone}}">
                                    </div>
                                </label>
                                <button type="submit" class="btn btn-primary">ارسال کد تایید</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/front/dashboard/profile.blade.php
@extends('front.layouts.app')
@section('content')
    <section class="single_content">
        <div class="container">
            <div class="fes-vendor-dashboard-wrap row">
                @include('front.layouts.dashboard-sidebar')
                <div class="fes-vendor-dashboard col-md-9">
                    <div class="single_description marg_top_20 rounded shadow">
                        <div class="description_product negarbin_all_vendor_dashboard negarbin_left_dashboard">
                            <form action="{{route('dashboard.profile.store')}}" method="post"
                                  enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="my-2">
                                    @include('front.layouts.notification')
                                    @if ($errors->any())
                                        <div class="alert alert-danger">
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </div>
                                    @endif
                                </div>
                                <h3>پروفایل</h3>
                                <br>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>
                                            <h6>نام : <span class="text-danger">*</span></h6>
                                            <div class="negarbin_dashboard_field">
                                                <input type="text" name="first_name"
                                                       value="{{auth()->user()->first_name}}">
                                            </div>
                                        </label>
                                        <label>
                                            <h6>ایمیل : <span class="text-danger">*</span></h6>
                                            <div class="negarbin_dashboard_field">
                                                <input type="email" name="email" value="{{auth()->user()->email}}"
                                                       placeholder="example@gmail.com">
                                            </div>
                                        </label>
                                        <div class="upload_avatar">
                                            <!-- Uploader  -->
                                            <div class="negarbin_dashboard_field">
                                                <h6>آپلود آواتار :</h6>
                                                <small class="text-muted">فایل شما نباید بزرگ تر از 120px باشد</small>
                                                <div id="file-upload-form" class="uploader">
                                                    <input id="file-upload" type="file" name="profile_avatar"
                                                           accept="image/*">
                                                    <label for="file-upload" id="file-drag">
                                                        @if(isset(auth()->user()->avatar))
                                                            <img id="file-image" alt="Preview"
                                                                 src="{{auth()->user()->adjusted_avatar}}">
                                                        @else
                                                            <img id="file-image" src="" alt="Preview" class="hidden">
                                                        @endif
                                                        <div id="start"
                                                             @if(isset(auth()->user()->avatar)) class="hidden" @endif>
                                                            <i class="fa fa-download" aria-hidden="true"></i>
                                                            <div>
                                                                <img width="80" height="80"
                                                                     alt="mountain"
                                                                     src="{{asset('assets/front/images/montain.svg')}}">
                                                            </div>
                                                            <div id="notimage" class="hidden">Please select an image
                                                            </div>
                                                            <span id="file-upload-btn" class="btn btn-primary">آپلود تصویر شاخص</span>
                                                        </div>
                                                        <div id="response" class="hidden">
                                                            <div id="messages"></div>
                                                            <progress class="progress" id="file-progress" value="0">
                                                                <span>0</span>%
                                                            </progress>
                                                        </div>
                                                    </label>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label>
                                            <h6>نام خانوادگی : </h6>
                                            <div class="negarbin_dashboard_field">
                                                <input type="text" name="last_name"
                                                       value="{{auth()->user()->last_name}}">
                                            </div>
                                        </label>
                                        <label>
                                            <h6>شماره همراه : <span class="text-danger">*</span></h6>
                                            <div class="negarbin_dashboard_field">
                                                <input type="tel" name="phone" placeholder="09123548962"
                                                       value="{{auth()->user()->phone}}" disabled>
                                                <a href="{{route('dashboard.profile.editPhone')}}"
                                                   target="_blank" style="font-size: 12px">
                                                    تغییر شماره همراه
                                                </a>
                                            </div>
                                        </label>
                                        <label>
                                            <h6>نام کاربری : <span class="text-danger">*</span></h6>
                                            <div class="negarbin_dashboard_field">
                                                <input type="tel" name="username" placeholder="username-123"
                                                       value="{{auth()->user()->username}}">
                                                <small class="text-muted">
                                                    فقط حروف انگلیسی، اعداد و خط تیره مجاز است.
                                                </small>
                                            </div>
                                        </label>
                                    </div>
                                </div>
                                <div class="row mb-4">
                                    <div class="col-md-12">
                                        <label>
                                            <h6>شماره شبا :</h6>
                                            <div class="negarbin_dashboard_field input-group flex-nowrap m-0">
                                                <input type="text" name="IBAN" class="dashboard-iban-field"
                                                       value="{{substr(auth()->user()->IBAN, 2)}}"
                                                       aria-describedby="ir-addon">
                                                <span class="input-group-text-dashboard" id="ir-addon">IR</span>
                                            </div>
                                            <small class="text-muted d-block">
                                                بدون فاصله و خط تیره
                                            </small>
                                        </label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="negarbin_dashboard_field">
                                        <input type="submit" name="profile_save" value="ذخیره"
                                               class="btn btn-success">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/front/dashboard/verify-phone.blade.php
@extends('front.layouts.app')
@section('content')
    <section class="single_content">
        <div class="container">
            <div class="fes-vendor-dashboard-wrap row">
                @include('front.layouts.dashboard-sidebar')
                <div class="fes-vendor-dashboard col-md-9">
                    <div class="single_description marg_top_20 rounded shadow">
                        <div class="description_product negarbin_all_vendor_dashboard negarbin_left_dashboard">
                            <form action="{{route('dashboard.profile.verifyPhone')}}" method="post">
                                @csrf
                                <div class="my-2">
                                    @include('front.layouts.notification')
                                    @if ($errors->any())
                                        <div class="alert alert-danger">
                                            @foreach ($errors->all() as $error)
                                                <li class="m-0">{{ $error }}</li>
                                            @endforeach
                                        </div>
                                    @endif
                                </div>
                                @if(session()->has('verifyUserPhone'))
                                    <div class="alert alert-info-bordered">
                                        شماره موبایل‌: {{session()->get('verifyUserPhone.phoneNumber')}}
                                    </div>
                                @endif
                                <label>
                                    <h6>تایید شماره موبایل : </h6>
                                    <div class="negarbin_dashboard_field">
                                        <input type="text" name="verify_code" placeholder="کد تایید ارسال شده را وارد نمایید">
                                    </div>
                                </label>
                                <button type="submit" class="btn btn-primary">ثبت شماره</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection